name: Deploy to EC2

on:
  push:
    branches:
      - main  # デプロイ対象のブランチ

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/your-project-path  # EC2上のプロジェクトディレクトリ
            git pull origin main
            docker-compose up -d --build
            docker-compose exec -T app php artisan migrate --force